### ISSUE TITLE
3 tests, 2 failed, 1 worked

### ISSUE THREAD

**Issue by AdAssassin** [simwai/referral-link-inserter#10]
My tag is `EXAMPLE`.

### Test 1, Which Worked

- Original Link `https://www.amazon.com/dp/B0BKC67D3V?tag=pcpapi-20&linkCode=ogi&th=1&psc=1`
- Goes go `https://www.amazon.com/dp/B0BKC67D3V/ref=nosim?tag=EXAMPLE&linkCode=ogi&th=1&psc=1`

### Test 2, Which Failed

- Original Link
`https://buy.geni.us/Proxy.ashx?TSID=3088&GR_URL=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB07PXGQC1Q%3Ftag%3Dmacrumors-20%26linkCode%3Dogi%26th%3D1%26psc%3D1`
- Goes to `https://www.amazon.ca/dp/B07PXGQC1Q?tag=macr05-20&geniuslink=true`
- As you can see, this extension couldnt change the TAG at this stage.
- So that's why I have to press the Refresh button on the URL, and then it worked
`https://www.amazon.ca/dp/B07PXGQC1Q/ref=nosim?tag=EXAMPLE&geniuslink=true`

### Test 3, Which Failed

- Original Link `https://amzn.to/49xs30P`
- Goes to `https://www.amazon.ca/dp/B0BJMGW6V3?th=1&linkCode=sl1&tag=eiv-20&linkId=8afc66082d293ecb6a1ec62a8ed8af7d&language=en_CA&ref_=as_li_ss_tl`
- As you can see, this extension couldnt change the TAG at this stage.
- So that's why I have to press the Refresh button on the URL, and then it worked `https://www.amazon.ca/dp/B0BJMGW6V3/ref=nosim?th=1&linkCode=sl1&tag=EXAMPLE&linkId=8afc66082d293ecb6a1ec62a8ed8af7d&language=en_CA&ref_=as_li_ss_tl`

These are the 3 tests that I just performed. 
Is there anything you can do to improve the algorithm, to catch change (and change) the TAG for Test 2 and Test 3?
If not, no big deal. Just wanted you to be aware of this limitation.

**Comment by simwai** [comment]
Thanks for the detailed report. I'll see what I can do.

**Comment by simwai** [comment]
I'll release today v1.9 which supports genius, but not the shortened Amazon URL. For the shortened URL I had no idea to fix it.
