### ISSUE TITLE
Looping on amazon.fr and amazon.es

### ISSUE THREAD

**Issue by 666dsa666** [simwai/referral-link-inserter#9]
Here is an example : 
https://www.amazon.fr/Funko-55972-POP-Disney-Princess/dp/B08P5YKK1N/ref=pd_rhf_gw_s_pd_sbs_rvi_d_sccl_1_2/260-9813773-7600216?pd_rd_w=LUdMd&content-id=amzn1.sym.9681233c-eae9-4b43-9735-758911d48926&pf_rd_p=9681233c-eae9-4b43-9735-758911d48926&pf_rd_r=NHG276NF4NDWSCT0PKFC&pd_rd_wg=XEdRG&pd_rd_r=d9551bc9-9a3f-4e9a-a61c-6f90313fe337&pd_rd_i=B08P5YKK1N&psc=1

Will redirect to : 

https://www.amazon.fr/dp/B08P5YKK1N/ref=olp-opf-redir?aod=1&ie=UTF8&condition=ALL&tag=xxx

But it will keep redirecting endlessly, same issue on amazon.es

**Comment by simwai** [comment]
Hm, that's weird. I cannot reproduce it. Check if you have the latest version.

I get redirected to:
https://www.amazon.fr/Funko-55972-POP-Disney-Princess/dp/B08P5YKK1N/ref=pd_rhf_gw_s_pd_sbs_rvi_d_sccl_1_2/260-9813773-7600216/ref=nosim?pd_rd_w=LUdMd&content-id=amzn1.sym.9681233c-eae9-4b43-9735-758911d48926&pf_rd_p=9681233c-eae9-4b43-9735-758911d48926&pf_rd_r=NHG276NF4NDWSCT0PKFC&pd_rd_wg=XEdRG&pd_rd_r=d9551bc9-9a3f-4e9a-a61c-6f90313fe337&pd_rd_i=B08P5YKK1N&tag=monztera-21&th=1

**Comment by 666dsa666** [comment]
Sadly yes I'm using 1.8, I've tried EDGE without any other add-on and also disabled my network ad blocker, I'll have a look at using chrome just in case
